version: '3'

services:
  backend: 
    image: wlguss/inspire-monolithic  # Dockerfile로 이미지를 생성해 hub에 업로드한 이미지를 내려받음 
    container_name: monolithic-backend-container
    ports:
      - "8080:8080" # 외부 접근용 포트:타깃 포트
    environment:
      # DB(mariadb)
      # RDS 사용시 발급받은 엔드포인트로 수정 
      SPRING_DATASOURCE_URL: jdbc:mariadb://lgcns-wlguss.clm4my0wcpvc.ap-south-1.rds.amazonaws.com:3306/inspire
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1215
      # JPA
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
      SPRING_JPA_SHOW_SQL: true
      # redis
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    restart: always
    depends_on:
      # RDS 사용시 제거
      # - database
      - redis
# AWS RDS 사용시 제거
  # database:
  #   image: wlguss/inspire-mariadb   # 허브에 등록된 이미지
  #   container_name: monolithic-mariadb-container
  #   ports:
  #     - "6033:3306"   # 배열 형식 
  #   environment:
  #     MARIADB_ROOT_PASSWORD: 1215
  #     MARIADB_DATABASE: inspire
  redis: 
    image: wlguss/inspire-redis
    container_name: monolithic-redis-container
    ports:
      - "6379:6379"
    restart: always