# aws - ecr image 
server:
    forward-headers-strategy: framework 

spring:
    datasource: # aws - rds 
        driver-class-name: org.mariadb.jdbc.Driver  # MariaDB와 연결할 수 있는 드라이버 클래스 
        url: jdbc:mariadb://${DB_HOST}:3306/inspire?useSSL=TRUE&requireSSL=true # k8s - secret에 담을 수 있음 
        username: ${DB_ADMIN}
        password: ${DB_PASSWORD}

    #redis
    data:
        redis:
            # host 설정은 order_redis.yaml의 서비스 이름과 mapping 
            host: redis-service 
            port: 6379
            password: 
            timeout: 6000ms


    jpa:
        hibernate: 
            # create(-> 서버 기동 시점에 생성된 entity에 매핑되는 테이블 자동 생성), create-drop, update, none
            ddl-auto:  create
        # 콘솔출력
        show-sql: true     
        properties:
            hibernate:
                # h2
                # dialect: org.hibernate.dialect.H2Dialect
                # mariadb
                dialect: org.hibernate.dialect.MariaDBDialect
                format_sql: true

jwt:
    secret: wlguss-jihyun-springsecurity-key-test-forjwtprovider-134679
